rabbit1:
  image: rabbitmq:3.6.6
  hostname: rabbit1
  cap_add:
    - ALL
    - NET_ADMIN
    - SYS_ADMIN
  environment:
    - RABBITMQ_ERLANG_COOKIE='storm'
  ports:
    - "1883:1883"
    - "5672:5672"
    - "8883:8883"
    - "15672:15672"

rabbit_final:
  image: rabbitmq:3.6.6
  hostname: rabbit2
  ports:
    - "1884:1883"
    - "5673:5672"
    - "8884:8883"
    - "15673:15672"

#rabbit2:
 # image: rabbitmq:3.6.6
  #hostname: rabbit2
  #cap_add:
   # - ALL
    #- NET_ADMIN
    #- SYS_ADMIN
  #links:
   # - rabbit1
  #environment:
   #- CLUSTERED=true
   #- CLUSTER_WITH=rabbit1
   #- RAM_NODE=true
   #- RABBITMQ_ERLANG_COOKIE='storm'
  #ports:
   #   - "1884:1883"
    #  - "5673:5672"
     # - "8884:8883"
      #- "15673:15672"

#rabbit3:
 # image: rabbitmq:3.6.6
  #hostname: rabbit3
  #cap_add:
   # - ALL
   # - NET_ADMIN
   # - SYS_ADMIN
 # links:
  #  - rabbit1
   # - rabbit2
  #environment:
  # - CLUSTERED=true
  # - CLUSTER_WITH=rabbit1
  # - RABBITMQ_ERLANG_COOKIE='storm'
  #ports:
  #    - "1885:1883"
   #   - "5674:5672"
   #   - "8885:8883"
   #   - "15674:15672"